# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 14

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Label to use when marking as stale
staleLabel: stale

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Limit the number of actions per hour, from 1-30. The default is 30.
limitPerRun: 15