version: "3.9"

services:
  telegram-forwarder:
    container_name: telegram-forwarder
    image: telegram-forwarder-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./chat_list.json:./chat_list.json
